app/dimensao_II/urls.py
API_MSC_PAT = 'https://apidatalake.tesouro.gov.br/ords/siconfi/tt/msc_patrimonial'
API_MSC_ORC = 'https://apidatalake.tesouro.gov.br/ords/siconfi/tt/msc_orcamentaria'
API_DCA = 'https://apidatalake.tesouro.gov.br/ords/siconfi/tt/dca'

app/routes/card_dimension.py
from flask import Blueprint, render_template

# Criação do blueprint para card_dimension
card_dimension_bp = Blueprint('card_dimension_bp', __name__)

@card_dimension_bp.route('/card_dimension', methods=['GET'])
def card_dimension():
    """
    Rota para a página 'card_dimension'.
    Carrega as opções de dimensões.
    """
    return render_template('card_dimension.html')  # Renderiza o template que contém os links para as dimensões

app/routes/dimensionii.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from concurrent.futures import ThreadPoolExecutor
from ..dimensao_II.dca.percent_valid import calcular_percentual

from ..dimensao_II.dca.anexos.dca_anexo_i_hi import(
    get_dca_i_hi, 
    d2_1_vpa_fundeb_principal, 
    d2_2_vpd_fundeb_principal
) 
from ..dimensao_II.dca.anexos.dca_anexo_i_c import(
    get_dca_i_c, 
    d2_3_deducoes_fundeb, 
    d2_4_receitas_fundeb,
    d2_10_receitas_outros_entes
)
from ..dimensao_II.dca.anexos.dca_anexo_i_d import (
    get_dca_i_d, 
    d2_5_desp_patronal_empenhada, 
    d2_6_desp_pessoal_empenhada, 
    d2_7_desp_custeio_empenhada
)
from ..dimensao_II.dca.anexos.dca_anexo_i_e import (
    get_dca_i_e, 
    d2_8_desp_por_funcao
)

dimensionii_bp = Blueprint('dimensionii_bp', __name__)

@dimensionii_bp.route('/dimensionii', methods=['GET'])
def dimensionii():
    id_ente = request.args.get('id_ente')
    an_referencia = request.args.get('an_referencia')
    
    if not id_ente or not an_referencia:
        flash("Parâmetros 'id_ente' e 'an_referencia' são necessários.", "warning")
        return redirect(url_for('home_bp.home'))

    # Executa as chamadas de API em paralelo
    with ThreadPoolExecutor() as executor:
        get_api_hi = executor.submit(get_dca_i_hi, id_ente, an_referencia)
        get_api_ic = executor.submit(get_dca_i_c, id_ente, an_referencia)
        get_api_id = executor.submit(get_dca_i_d, id_ente, an_referencia)
        get_api_ie = executor.submit(get_dca_i_e, id_ente, an_referencia)

        anexo_i_hi = get_api_hi.result()
        anexo_ic = get_api_ic.result()
        anexo_id = get_api_id.result()
        anexo_ie = get_api_ie.result()

    # Processa os resultados das validações conforme cada anexo
    d2_01 = d2_1_vpa_fundeb_principal(anexo_i_hi)
    d2_02 = d2_2_vpd_fundeb_principal(anexo_i_hi)
    d2_03 = d2_3_deducoes_fundeb(anexo_ic)
    d2_04 = d2_4_receitas_fundeb(anexo_ic)
    d2_05 = d2_5_desp_patronal_empenhada(anexo_id)
    d2_06 = d2_6_desp_pessoal_empenhada(anexo_id)
    d2_07 = d2_7_desp_custeio_empenhada(anexo_id)
    d2_08 = d2_8_desp_por_funcao(anexo_ie)
    d2_10 = d2_10_receitas_outros_entes(anexo_ic)

    # Calcula os percentuais de 'Dado Consistente' e 'Dado Divergente'
    percentuais = calcular_percentual({
        'd2_01': d2_01,
        'd2_02': d2_02,
        'd2_03': d2_03,
        'd2_04': d2_04,
        'd2_05': d2_05,
        'd2_06': d2_06,
        'd2_07': d2_07,
        'd2_08': d2_08,
        'd2_10': d2_10
    })

    # Formata os percentuais sem casas decimais e adiciona o símbolo de '%'
    percentual_consistente = f"{int(percentuais['Percentual Consistente'])}%"
    percentual_divergente = f"{int(percentuais['Percentual Divergente'])}%"
    total_percentual = f"{int(percentuais['Total Percentual'])}%"  # Total como 100%


    # Renderiza o template com os resultados e os percentuais
    return render_template(
        'dimension_ii.html',
        d2_01=d2_01,
        d2_02=d2_02,
        d2_03=d2_03,
        d2_04=d2_04,
        d2_05=d2_05,
        d2_06=d2_06,
        d2_07=d2_07,
        d2_08=d2_08,
        d2_10=d2_10,
        total_itens=total_percentual,
        percentual_consistente=percentual_consistente, 
        percentual_divergente=percentual_divergente
    )

app/routes/dimensioniii.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from ..utils.format_currency import format_currency  # Importando a função de formatação de moeda

# Criação do blueprint para o dimensioniii
dimensioniii_bp = Blueprint('dimensioniii_bp', __name__)

@dimensioniii_bp.route('/dimensioniii', methods=['GET'])
def dimensioniii():
    id_ente = request.args.get('id_ente')
    an_referencia = request.args.get('an_referencia')

    # logging.info(f"Carregando dados para Dimensão III: id_ente={id_ente}, an_referencia={an_referencia}")

    if not id_ente or not an_referencia:
        flash("Parâmetros 'id_ente' e 'an_referencia' são necessários.", "warning")
        return redirect(url_for('home_bp.home'))


    return render_template('dimension_iii.html')

app/routes/dimensioniv.py
import logging
from flask import Blueprint, render_template, request, redirect, url_for, flash
from ..utils.format_currency import format_currency  # Importando a função de formatação de moeda


# Criação do blueprint para o dimensioniv
dimensioniv_bp = Blueprint('dimensioniv_bp', __name__)

@dimensioniv_bp.route('/dimensioniv', methods=['GET'])
def dimensioniv():
    id_ente = request.args.get('id_ente')
    an_referencia = request.args.get('an_referencia')
    

    # logging.info(f"Carregando dados para Dimensão IV: id_ente={id_ente}, an_referencia={an_referencia}")

    if not id_ente or not an_referencia:
        flash("Parâmetros 'id_ente' e 'an_referencia' são necessários.", "warning")
        return redirect(url_for('home_bp.home'))

    return render_template('dimension_iv.html')

app/routes/home.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, flash
import requests  # Para fazer a requisição externa à API
from ..utils.entes import get_ufs_cidades
from ..utils.period import get_anos

# Criação do blueprint para o home
home_bp = Blueprint('home_bp', __name__)

@home_bp.route('/')
def home():
    """
    Rota principal que carrega a página inicial.
    Verifica se a API de entes está disponível antes de carregar a página.
    """
    response = requests.get('https://apidatalake.tesouro.gov.br/ords/siconfi/tt/entes')
    
    # Verifica se a resposta da API foi bem-sucedida
    if response.status_code != 200:
        flash("Base de Dados Indisponível", "danger")
        return render_template('home.html', ufs=[], anos=[], cidades=[])

    ufs, cidades = get_ufs_cidades()
    anos = get_anos()
    return render_template('home.html', ufs=ufs, anos=anos, cidades=cidades)

@home_bp.route('/enviar_parans', methods=['POST'])
def enviar_parans():
    id_ente = request.form.get('id_ente')
    an_referencia = request.form.get('an_referencia')
    # nome_cidade = request.form.get('nome_cidade')  # Captura o nome da cidade

    if not id_ente or not an_referencia:
        flash("Por favor, forneça todos os parâmetros necessários.", "warning")
        return redirect(url_for('home_bp.home'))

    return redirect(url_for('card_dimension_bp.card_dimension', id_ente=id_ente, an_referencia=an_referencia))

@home_bp.route('/get_cidades/<uf>', methods=['GET'])
def get_cidades(uf):
    """
    Rota que retorna as cidades com base no estado (UF) selecionado.
    Faz uma requisição externa para obter os dados das cidades.
    """
    response = requests.get('https://apidatalake.tesouro.gov.br/ords/siconfi/tt/entes')
    
    if response.status_code == 200:
        data = response.json()['items']
        cidades = [item for item in data if item['uf'] == uf]
        return jsonify(cidades)
    else:
        return jsonify({"error": "Erro ao buscar cidades"}), 500

app/views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, current_app
import os
from .functions.entes import get_ufs_cidades
from .functions.periodo import get_anos
import requests

# Criação do blueprint
main = Blueprint('main', __name__)

# Rota que renderiza a página inicial (home)
@main.route('/')
def home():
    # Obter os dados iniciais de UFs, cidades, anos e meses
    ufs, cidades = get_ufs_cidades()
    anos= get_anos()
    
    return render_template('home.html', ufs=ufs, anos=anos, cidades=cidades)

# Rota que recebe os parâmetros do formulário e redireciona para a página de dimensões
@main.route('/enviar_parans', methods=['POST'])
def enviar_parans():
    # Captura os parâmetros enviados pelo formulário
    id_ente = request.form['id_ente']
    an_referencia = request.form['an_referencia']

    # Você pode adicionar a lógica para processar os dados aqui, se necessário
    
    # Redirecionar para a página de dimensões após enviar os parâmetros
    return redirect(url_for('main.card_dimension'))

# Rota para renderizar a página main_dimensoes
@main.route('/card_dimension')
def card_dimension():
    # Renderizar o template main_dimensoes.html
    return render_template('card_dimension.html')

# Rota para Dimensão II
@main.route('/dimension_ii')
def dimension_ii():
    return render_template('dimension_ii.html')

# Rota para Dimensão III
@main.route('/dimension_iii')
def dimension_iii():
    # Código de depuração para verificar o caminho do template
    print("Template path:", os.path.join(current_app.root_path, 'templates', 'dimension_iii.html'))
    
    return render_template('dimension_iii.html')

# Rota para Dimensão IV
@main.route('/dimension_iv')
def dimension_iv():
    return render_template('dimension_iv.html')

# Rota que retorna as cidades baseadas na UF
@main.route('/get_cidades/<uf>', methods=['GET'])
def get_cidades(uf):
    response = requests.get('https://apidatalake.tesouro.gov.br/ords/siconfi/tt/entes')
    data = response.json()['items']
    
    cidades = [item for item in data if item['uf'] == uf]
    return jsonify(cidades)

app/templates/card_dimension.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Dimensões</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container text-center mt-5">
    <h1>Selecione uma Dimensão</h1>
    <div class="row mt-4">
        <!-- Card para Dimensão II -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dimensão II</h5>
                 


                    <a href="{{ url_for('dimensionii_bp.dimensionii', id_ente=request.args.get('id_ente'), an_referencia=request.args.get('an_referencia')) }}" class="btn btn-primary">Acessar Dimensão II</a>
                </div>
            </div>
        </div>

        <!-- Card para Dimensão III -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dimensão III</h5>
                    <p class="card-text">Clique para acessar a página da Dimensão III.</p>
                    <a href="{{ url_for('dimensioniii_bp.dimensioniii', id_ente=request.args.get('id_ente'), an_referencia=request.args.get('an_referencia')) }}" class="btn btn-primary">Acessar Dimensão III</a>
                </div>
            </div>
        </div>

        <!-- Card para Dimensão IV -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dimensão IV</h5>
                    <p class="card-text">Clique para acessar a página da Dimensão IV.</p>
                    <a href="{{ url_for('dimensioniv_bp.dimensioniv', id_ente=request.args.get('id_ente'), an_referencia=request.args.get('an_referencia')) }}" class="btn btn-primary">Acessar Dimensão IV</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container text-center mt-5">
        <a href="{{ url_for('home_bp.home') }}" class="btn btn-secondary">Voltar para Home</a>
    </div>
</div>

</body>
</html>

app/templates/dimensao_ii.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dimensão II</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container text-center mt-5">
        <h1>Dimensão II</h1>
        <p>Conteúdo da página Dimensão II</p>
        <a href="{{ url_for('main.main_dimensoes') }}" class="btn btn-secondary">Voltar para Dimensões</a>
        <a href="{{ url_for('main.home') }}" class="btn btn-secondary">Voltar para Home</a>
    </div>
</body>
</html>

app/templates/dimensao_iii.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dimensão III</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container text-center mt-5">
        <h1>Dimensão III</h1>
        <p>Conteúdo da página Dimensão III</p>
        <a href="{{ url_for('main.main_dimensoes') }}" class="btn btn-secondary">Voltar para Dimensões</a>
        <a href="{{ url_for('main.home') }}" class="btn btn-secondary">Voltar para Home</a>
    </div>
</body>
</html>

app/templates/dimensao_iv.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dimensão IV</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container text-center mt-5">
        <h1>Dimensão IV</h1>
        <p>Conteúdo da página Dimensão IV</p>
        <a href="{{ url_for('main.main_dimensoes') }}" class="btn btn-secondary">Voltar para Dimensões</a>
        <a href="{{ url_for('main.home') }}" class="btn btn-secondary">Voltar para Home</a>
        </div>
    </div>
</body>
</html>

app/templates/dimension_iii.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dimensão III</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container text-center mt-5">
        <h2>Em desenvolvimento</h2>
        
        <!-- Botões para voltar -->
        <div class="mt-4">
            <a href="{{ url_for('card_dimension_bp.card_dimension', id_ente=request.args.get('id_ente'), an_referencia=request.args.get('an_referencia')) }}" class="btn btn-secondary">Voltar para Dimensões</a>
            <a href="{{ url_for('home_bp.home') }}" class="btn btn-secondary">Voltar para Home</a>
        </div>
    </div>
</body>
</html>

app/templates/dimension_iv.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dimensão IV</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container text-center mt-5">
        <h2><h2>Em desenvolvimento</h2></h2>
        
        <!-- Botões para voltar -->
        <div class="mt-4">
            <a href="{{ url_for('card_dimension_bp.card_dimension', id_ente=request.args.get('id_ente'), an_referencia=request.args.get('an_referencia')) }}" class="btn btn-secondary">Voltar para Dimensões</a>
            <a href="{{ url_for('home_bp.home') }}" class="btn btn-secondary">Voltar para Home</a>
        </div>
    </div>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Dimensões</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container mt-4">
        <!-- Exibir mensagens flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <!-- Formulário de seleção de parâmetros -->
        <form action="{{ url_for('home_bp.enviar_parans') }}" method="POST" class="form-container mt-5">
            <div class="form-group mt-3">
                <label for="an_referencia">Exercício:</label>
                <select id="an_referencia" name="an_referencia" class="form-control form-control-sm" required>
                    <option value="">Selecione</option>
                    {% for ano in anos %}
                        <option value="{{ ano }}">{{ ano }}</option>
                    {% endfor %}
                </select>
            </div>
            
            <div class="form-group mt-4">
                <label for="uf">UF:</label>
                <select class="form-control form-control-sm" id="uf" name="uf" required>
                    <option value="">Selecione</option>
                    {% for uf in ufs %}
                        <option value="{{ uf }}">{{ uf }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group position-relative mt-4">
                <label for="ente">Cidade:</label>
                <div class="input-group">
                    <select class="form-control form-control-sm" id="ente" name="ente" disabled required>
                        <option value="">Cidade</option>
                    </select>
                    <span id="loading-text" class="text-primary d-none position-absolute" style="top: 50%; left: 85%; transform: translate(-50%, -50%);">
                        Carregando...
                    </span>
                </div>
            </div>

            <div class="form-group d-none mt-4">
                <label for="id_ente" class="sr-only">IBGE</label>  
                <input type="text" id="id_ente" name="id_ente" class="form-control form-control-sm" placeholder="IBGE" size="5" required />
            </div>
            
            <button type="submit" class="btn btn-primary btn-sm btn-block mt-5 btn-custom-height">Entrar</button>
        </form>
    </div>
    
    <script src="{{ url_for('static', filename='js/selectcity.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>      
   
</body>
</html>

app/templates/main_dimensoes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Dimensões</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<div class="container text-center mt-5">
    <h1>Selecione uma Dimensão</h1>
    <div class="row mt-4">
        <!-- Card para Dimensão II -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dimensão II</h5>
                    <p class="card-text">Clique para acessar a página da Dimensão II.</p>
                    <a href="{{ url_for('main.dimensao_ii') }}" class="btn btn-primary">Acessar Dimensão II</a>
                </div>
            </div>
        </div>

        <!-- Card para Dimensão III -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dimensão III</h5>
                    <p class="card-text">Clique para acessar a página da Dimensão III.</p>
                    <a href="{{ url_for('main.dimensao_iii') }}" class="btn btn-primary">Acessar Dimensão III</a>
                </div>
            </div>
        </div>

        <!-- Card para Dimensão IV -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Dimensão IV</h5>
                    <p class="card-text">Clique para acessar a página da Dimensão IV.</p>
                    <a href="{{ url_for('main.dimensao_iv') }}" class="btn btn-primary">Acessar Dimensão IV</a>
                </div>
            </div>
        </div>
        <div class="container text-center mt-5">
            <a href="{{ url_for('main.home') }}" class="btn btn-secondary">Voltar para Home</a>
        </div>
    </div>
</div>